
import Footer from "./components/footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
            

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Navbar/>
        <Footer/>
      </body>
    </html>
  );
}